export const TYPES = {
    User: Symbol.for('User'),
    UserDetail: Symbol.for('UserDetail'),
    Role: Symbol.for('Role'),
    Order: Symbol.for('Order'),
    NewlyContract: Symbol.for('NewlyContract'),
    PlatformEvent: Symbol.for('PlatformEvent'),
    UserOperatingData: Symbol.for('UserOperatingData'),
    UserCompetence: Symbol.for('UserCompetence'),
    Room: Symbol.for('Room'),
    Message: Symbol.for('Message'),

    UserService: Symbol.for('UserService'),
    RegistrationService: Symbol.for('RegistrationService'),
    LoginService: Symbol.for('LoginService'),
    OrderService: Symbol.for('OrderService'),
    EventService: Symbol.for('EventService'),
    NewlyContractService: Symbol.for('NewlyContractService'),
    EventOrderService: Symbol.for('EventOrderService'),
    UserDetailService: Symbol.for('UserDetailService'),
    UserCompetenceService: Symbol.for('UserCompetenceService'),
    UserOperatingDataService: Symbol.for('UserOperatingDataService'),
    RoomService: Symbol.for('RoomService'),
    MessageService: Symbol.for('MessageService'),

    OrderInteractor: Symbol.for('OrderInteractor'),
    UserInteractor: Symbol.for('UserInteractor'),
    RegistrationInteractor: Symbol.for('RegistrationInteractor'),
    ChatInteractor: Symbol.for('ChatInteractor'),

    ConnectionStore: Symbol.for('ConnectionStore'),
    ChatEventEmitter: Symbol.for('ChatEventEmmitor'),
    ChatController: Symbol.for('ChatController'),
};

